### ISSUE TITLE
Issue with Oral Histories View

### ISSUE THREAD

**Issue by darnelleMelvin** [UNLV-Libraries/wikidata-discovery-project#10]
When searching for an oral history, the returned result do not show the subjects within the graph view. If you hover over the node, you only get the name, inventory number, and described at properties.  Also, when you click on the details for that oral history, the main subjects and the described at properties are not in the results, but that data is in the [wikidata entity](https://www.wikidata.org/wiki/Q111011414). 

![20230615_wikiframe_error002](https://github.com/UNLV-Libraries/wikidata-discovery-project/assets/32146321/a7ead082-a748-4031-8784-396cefd2f8d4)
![20230615_wikiframe_error001](https://github.com/UNLV-Libraries/wikidata-discovery-project/assets/32146321/5942d85a-4b5a-4d28-bcdc-01907c13c6a7)

**Comment by aehulet** [comment]
Resolved, but note that in our oral histories data, 'human' items are set as main subject values, which can create inconsistent presentation of oral history results data.
