### ISSUE TITLE
Problem drawing graph in Oral Histories facet

### ISSUE THREAD

**Issue by darnelleMelvin** [UNLV-Libraries/wikidata-discovery-project#11]
Got this error when searching in Oral Histories facet. The problem is with [Ruby Duncan](https://www.wikidata.org/entity/Q19957642)
Can we work on dropping the node if this type of error occurs? I believe we found a similar error with one of our [Nevada mines](https://www.wikidata.org/entity/Q105401698). 

![20230615_wikiframe_error003](https://github.com/UNLV-Libraries/wikidata-discovery-project/assets/32146321/a2f4058f-6928-4d02-9700-6ae4668422ea)

**Comment by aehulet** [comment]
resolved
