### ISSUE TITLE
Update Request: Home Page

### ISSUE THREAD

**Issue by darnelleMelvin** [UNLV-Libraries/wikidata-discovery-project#12]
The current homepage just says "This is a home page". We should update the previous text with the [introduction section](https://github.com/UNLV-Libraries/wikidata-discovery-project) of our readme file for the repo. Please update text with the following:</br>

<p>
Welcome to wikiframeVG (Wikiframe Visual Graph), an open-source community initiative and tool aimed to help Wikidata editors and users explore knowledge generated from organized Wikidata sprints. wikiframeVG adopts a community driven, SPARQL template-based approach towards Wikidata graph exploration.</p>
<p>
The application interacts with Wikidata's SPARQL[ query service](https://query.wikidata.org/) and provides users with point-and-click tools to search and filter information. No SPARQL or other coding knowledge will be required to retrieve data linked across the Wikidata knowledge graph.</p>

**Comment by aehulet** [comment]
@darnelleMelvin Home page content updated. Will show up in next deployment.
