### ISSUE TITLE
Update Request: add hyperlinks to all identifier urls

### ISSUE THREAD

**Issue by darnelleMelvin** [UNLV-Libraries/wikidata-discovery-project#13]
I noticed within the results view after you click on the details tab, some entities have a variety of external uris. Some examples are links to LCNAF, VIAF, find a grave identifiers, etc. I would like a update that makes those values hyperlinked, so when a user clicks on them, a new browser tab resolves to that authority.

**Comment by aehulet** [comment]
Current solution maintains list in code that hyperlinks named identfiers when item page loads.
